import {
  Transaction,
  CreditCard,
  FinancialGoal,
  Debt,
  Alert,
  Budget,
} from '../types';

const now = new Date();
const getDateDaysAgo = (days: number): string => {
  const date = new Date(now);
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

const getMonthString = (date: Date): string => {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  return `${year}-${month}`;
};

export const mockTransactions: Transaction[] = [
  {
    id: 'txn_1',
    type: 'income',
    amount: 5000,
    description: 'Salario mensual',
    category: 'salary',
    tags: ['salario', 'mensual'],
    date: getDateDaysAgo(0),
    paymentMethod: 'bank_transfer',
    createdAt: getDateDaysAgo(0),
    updatedAt: getDateDaysAgo(0),
  },
  {
    id: 'txn_2',
    type: 'expense',
    amount: 150.50,
    description: 'Supermercado',
    category: 'food',
    tags: ['compras', 'semanal'],
    date: getDateDaysAgo(1),
    paymentMethod: 'card',
    cardId: 'card_1',
    createdAt: getDateDaysAgo(1),
    updatedAt: getDateDaysAgo(1),
  },
  {
    id: 'txn_3',
    type: 'expense',
    amount: 45.00,
    description: 'Gasolina',
    category: 'transport',
    tags: ['combustible'],
    date: getDateDaysAgo(2),
    paymentMethod: 'card',
    cardId: 'card_1',
    createdAt: getDateDaysAgo(2),
    updatedAt: getDateDaysAgo(2),
  },
  {
    id: 'txn_4',
    type: 'expense',
    amount: 1200.00,
    description: 'Alquiler',
    category: 'housing',
    tags: ['vivienda', 'mensual'],
    date: getDateDaysAgo(3),
    paymentMethod: 'bank_transfer',
    createdAt: getDateDaysAgo(3),
    updatedAt: getDateDaysAgo(3),
  },
  {
    id: 'txn_5',
    type: 'expense',
    amount: 85.00,
    description: 'Netflix + Spotify',
    category: 'entertainment',
    tags: ['suscripciones'],
    date: getDateDaysAgo(5),
    paymentMethod: 'card',
    cardId: 'card_2',
    createdAt: getDateDaysAgo(5),
    updatedAt: getDateDaysAgo(5),
  },
  {
    id: 'txn_6',
    type: 'expense',
    amount: 65.00,
    description: 'Luz y agua',
    category: 'utilities',
    tags: ['servicios'],
    date: getDateDaysAgo(7),
    paymentMethod: 'bank_transfer',
    createdAt: getDateDaysAgo(7),
    updatedAt: getDateDaysAgo(7),
  },
  {
    id: 'txn_7',
    type: 'income',
    amount: 500,
    description: 'Freelance proyecto web',
    category: 'other_income',
    tags: ['freelance', 'extra'],
    date: getDateDaysAgo(10),
    paymentMethod: 'bank_transfer',
    createdAt: getDateDaysAgo(10),
    updatedAt: getDateDaysAgo(10),
  },
  {
    id: 'txn_8',
    type: 'expense',
    amount: 250.00,
    description: 'Farmacia + Doctor',
    category: 'health',
    tags: ['salud', 'medicamentos'],
    date: getDateDaysAgo(12),
    paymentMethod: 'card',
    cardId: 'card_1',
    createdAt: getDateDaysAgo(12),
    updatedAt: getDateDaysAgo(12),
  },
  {
    id: 'txn_9',
    type: 'expense',
    amount: 180.00,
    description: 'Libros programación',
    category: 'education',
    tags: ['cursos', 'estudio'],
    date: getDateDaysAgo(15),
    paymentMethod: 'card',
    cardId: 'card_2',
    createdAt: getDateDaysAgo(15),
    updatedAt: getDateDaysAgo(15),
  },
  {
    id: 'txn_10',
    type: 'expense',
    amount: 89.99,
    description: 'Zapatos',
    category: 'shopping',
    tags: ['ropa'],
    date: getDateDaysAgo(18),
    paymentMethod: 'card',
    cardId: 'card_1',
    createdAt: getDateDaysAgo(18),
    updatedAt: getDateDaysAgo(18),
  },
];

export const mockCards: CreditCard[] = [
  {
    id: 'card_1',
    name: 'Visa Platinum',
    lastFourDigits: '4532',
    limit: 5000,
    currentBalance: 1250,
    dueDate: '2026-03-15',
    closingDate: '2026-03-25',
    brand: 'visa',
    color: '#1E3A5F',
    createdAt: getDateDaysAgo(90),
  },
  {
    id: 'card_2',
    name: 'Mastercard Gold',
    lastFourDigits: '8901',
    limit: 3000,
    currentBalance: 450,
    dueDate: '2026-03-20',
    closingDate: '2026-03-28',
    brand: 'mastercard',
    color: '#C62828',
    createdAt: getDateDaysAgo(180),
  },
];

export const mockGoals: FinancialGoal[] = [
  {
    id: 'goal_1',
    name: 'Vacaciones',
    targetAmount: 3000,
    currentAmount: 1500,
    category: 'travel',
    deadline: '2026-06-30',
    status: 'active',
    createdAt: getDateDaysAgo(60),
  },
  {
    id: 'goal_2',
    name: 'Emergencias',
    targetAmount: 10000,
    currentAmount: 7000,
    category: 'emergency',
    deadline: '2026-12-31',
    status: 'active',
    createdAt: getDateDaysAgo(120),
  },
  {
    id: 'goal_3',
    name: 'Nuevo Laptop',
    targetAmount: 2000,
    currentAmount: 500,
    category: 'technology',
    deadline: '2026-09-01',
    status: 'active',
    createdAt: getDateDaysAgo(30),
  },
];

export const mockDebts: Debt[] = [
  {
    id: 'debt_1',
    name: 'Préstamo personal',
    totalAmount: 10000,
    remainingAmount: 7500,
    interestRate: 12,
    monthlyPayment: 450,
    dueDate: '2027-03-01',
    creditor: 'Banco Nacional',
    status: 'active',
    createdAt: getDateDaysAgo(180),
  },
  {
    id: 'debt_2',
    name: 'Financiamiento auto',
    totalAmount: 20000,
    remainingAmount: 15000,
    interestRate: 8,
    monthlyPayment: 550,
    dueDate: '2030-01-01',
    creditor: 'Banco Automotriz',
    status: 'active',
    createdAt: getDateDaysAgo(365),
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'alert_1',
    title: 'Pago tarjeta Visa',
    description: 'Fecha de vencimiento de tarjeta Visa Platinum',
    type: 'payment',
    dueDate: '2026-03-15',
    isCompleted: false,
    notifyPush: true,
    notifyEmail: true,
    createdAt: getDateDaysAgo(5),
  },
  {
    id: 'alert_2',
    title: 'Presupuesto alimentación',
    description: 'Has alcanzado el 80% del presupuesto de alimentación',
    type: 'budget',
    dueDate: '2026-03-10',
    isCompleted: false,
    notifyPush: true,
    notifyEmail: false,
    createdAt: getDateDaysAgo(3),
  },
  {
    id: 'alert_3',
    title: 'Pago préstamo',
    description: 'Cuota mensual del préstamo personal',
    type: 'debt',
    dueDate: '2026-03-01',
    isCompleted: true,
    notifyPush: true,
    notifyEmail: true,
    createdAt: getDateDaysAgo(15),
  },
  {
    id: 'alert_4',
    title: 'Meta vacaciones',
    description: 'Aporta a tu meta de vacaciones este mes',
    type: 'goal',
    dueDate: '2026-03-31',
    isCompleted: false,
    notifyPush: false,
    notifyEmail: true,
    createdAt: getDateDaysAgo(1),
  },
  {
    id: 'alert_5',
    title: 'Cierre tarjeta Mastercard',
    description: 'El cierre del ciclo de Mastercard Gold es mañana',
    type: 'payment',
    dueDate: '2026-03-27',
    isCompleted: false,
    notifyPush: true,
    notifyEmail: false,
    createdAt: getDateDaysAgo(2),
  },
];

export const mockBudgets: Budget[] = [
  {
    id: 'budget_1',
    category: 'food',
    amount: 600,
    spent: 450,
    month: getMonthString(now),
    createdAt: getDateDaysAgo(1),
  },
  {
    id: 'budget_2',
    category: 'transport',
    amount: 200,
    spent: 120,
    month: getMonthString(now),
    createdAt: getDateDaysAgo(1),
  },
  {
    id: 'budget_3',
    category: 'entertainment',
    amount: 150,
    spent: 135,
    month: getMonthString(now),
    createdAt: getDateDaysAgo(1),
  },
  {
    id: 'budget_4',
    category: 'shopping',
    amount: 300,
    spent: 180,
    month: getMonthString(now),
    createdAt: getDateDaysAgo(1),
  },
  {
    id: 'budget_5',
    category: 'utilities',
    amount: 200,
    spent: 65,
    month: getMonthString(now),
    createdAt: getDateDaysAgo(1),
  },
];
